const P2H_DATA = {
  "Articulate Truck": [
    {id:101,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:102,item:"Oli Engine",hazard:"AA",section:""},
    {id:103,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:104,item:"Air Radiator",hazard:"AA",section:""},
    {id:105,item:"Oli Transmisi",hazard:"A",section:""},
    {id:106,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:107,item:"Drain Water Separator",hazard:"B",section:""},
    {id:108,item:"Drain Compressor Tank",hazard:"B",section:""},
    {id:109,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:110,item:"Handrail / Tangga",hazard:"A",section:""},
    {id:111,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:112,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:113,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:114,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:115,item:"Lampu",hazard:"A",section:""},
    {id:116,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:117,item:"Wiper",hazard:"A",section:""},
    {id:118,item:"Klakson",hazard:"AA",section:""},
    {id:119,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:120,item:"Control Panel",hazard:"A",section:""},
    {id:121,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:122,item:"Radio",hazard:"AA",section:""},
    {id:123,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:124,item:"Safety Cone",hazard:"A",section:""},
    {id:125,item:"Wheel Chock",hazard:"A",section:""},
    {id:126,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:127,item:"Emergency Stop",hazard:"A",section:""},
    {id:128,item:"Fog Lamp",hazard:"A",section:""},
    {id:129,item:"Dashcam",hazard:"A",section:""},
    {id:130,item:"Commissioning",hazard:"AA",section:""},
    {id:131,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Bulldozer": [
    {id:201,item:"Oli Engine",hazard:"AA",section:""},
    {id:202,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:203,item:"Air Radiator",hazard:"AA",section:""},
    {id:204,item:"Oli Transmisi",hazard:"A",section:""},
    {id:205,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:206,item:"Drain Water Separator",hazard:"B",section:""},
    {id:207,item:"Kondisi Blade",hazard:"B",section:""},
    {id:208,item:"Handrail / Tangga",hazard:"A",section:""},
    {id:209,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:210,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:211,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:212,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:213,item:"Lampu",hazard:"A",section:""},
    {id:214,item:"Wiper",hazard:"A",section:""},
    {id:215,item:"Klakson",hazard:"AA",section:""},
    {id:216,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:217,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:218,item:"Control Panel",hazard:"A",section:""},
    {id:219,item:"Radio",hazard:"AA",section:""},
    {id:220,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:221,item:"Safety Cone",hazard:"A",section:""},
    {id:222,item:"Emergency Stop",hazard:"A",section:""},
    {id:223,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:224,item:"Fog Lamp",hazard:"A",section:""},
    {id:225,item:"Commissioning",hazard:"AA",section:""},
    {id:226,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Compactor": [
    {id:301,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:302,item:"Oil Engine",hazard:"AA",section:""},
    {id:303,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:304,item:"Air Radiator",hazard:"AA",section:""},
    {id:305,item:"Oil Vibrator (dalam Drum)",hazard:"A",section:""},
    {id:306,item:"Oil Hidrolik",hazard:"A",section:""},
    {id:307,item:"Fuel Drain",hazard:"B",section:""},
    {id:308,item:"Water Compressor Drain",hazard:"B",section:""},
    {id:309,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:310,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:311,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:312,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:313,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:314,item:"Lampu",hazard:"A",section:""},
    {id:315,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:316,item:"Wiper",hazard:"A",section:""},
    {id:317,item:"Klakson",hazard:"AA",section:""},
    {id:318,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:319,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:320,item:"Radio",hazard:"AA",section:""},
    {id:321,item:"Control Panel",hazard:"A",section:""},
    {id:322,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:323,item:"Safety Cone",hazard:"A",section:""},
    {id:324,item:"Wheel Chock",hazard:"A",section:""},
    {id:325,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:326,item:"Emergency Stop",hazard:"A",section:""},
    {id:327,item:"Fog Lamp",hazard:"A",section:""},
    {id:328,item:"Commissioning",hazard:"AA",section:""},
    {id:329,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Dump Truck": [
    {id:401,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:402,item:"Oli Engine",hazard:"AA",section:""},
    {id:403,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:404,item:"Air Radiator",hazard:"AA",section:""},
    {id:405,item:"Oli Transmisi",hazard:"A",section:""},
    {id:406,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:407,item:"Drain Water Separator",hazard:"B",section:""},
    {id:408,item:"Drain Compressor Tank",hazard:"B",section:""},
    {id:409,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:410,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:411,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:412,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:413,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:414,item:"Lampu",hazard:"A",section:""},
    {id:415,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:416,item:"Wiper",hazard:"A",section:""},
    {id:417,item:"Klakson",hazard:"AA",section:""},
    {id:418,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:419,item:"Control Panel",hazard:"A",section:""},
    {id:420,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:421,item:"Radio",hazard:"AA",section:""},
    {id:422,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:423,item:"Safety Cone",hazard:"A",section:""},
    {id:424,item:"Wheel Chock",hazard:"A",section:""},
    {id:425,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:426,item:"Emergency Stop",hazard:"A",section:""},
    {id:427,item:"Fog Lamp",hazard:"A",section:""},
    {id:428,item:"Dashcam",hazard:"A",section:""},
    {id:429,item:"Commissioning",hazard:"AA",section:""},
    {id:430,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Excavator": [
    {id:501,item:"Oli Engine",hazard:"AA",section:""},
    {id:502,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:503,item:"Air Radiator",hazard:"AA",section:""},
    {id:504,item:"Oli PTO",hazard:"A",section:""},
    {id:505,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:506,item:"Oli Swing",hazard:"A",section:""},
    {id:507,item:"Drain Water Separator",hazard:"B",section:""},
    {id:508,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:509,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:510,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:511,item:"Lampu",hazard:"A",section:""},
    {id:512,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:513,item:"Wiper",hazard:"A",section:""},
    {id:514,item:"Klakson",hazard:"AA",section:""},
    {id:515,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:516,item:"Control Panel",hazard:"A",section:""},
    {id:517,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:518,item:"Radio",hazard:"AA",section:""},
    {id:519,item:"Safety Cone",hazard:"A",section:""},
    {id:520,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:521,item:"Emergency Stop",hazard:"A",section:""},
    {id:522,item:"Fog Lamp",hazard:"A",section:""},
    {id:523,item:"Commissioning",hazard:"AA",section:""},
    {id:524,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Light Vehicle": [
    {id:601,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:602,item:"Level Oli Engine",hazard:"AA",section:""},
    {id:603,item:"Air Radiator",hazard:"AA",section:""},
    {id:604,item:"Level Oli Steering",hazard:"A",section:""},
    {id:605,item:"Level Oli Rem (Break Oil)",hazard:"A",section:""},
    {id:606,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:607,item:"Lampu Rotary (Strobe Lamp)",hazard:"AA",section:""},
    {id:608,item:"Buggy Whip",hazard:"AA",section:""},
    {id:609,item:"Kondisi Battery / Accu",hazard:"A",section:""},
    {id:610,item:"Air Wiper",hazard:"A",section:""},
    {id:611,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:612,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:613,item:"Fungsi Steering / Reaksi Kemudi",hazard:"AA",section:""},
    {id:614,item:"Fungsi Seat Belt / Sabuk Pengaman",hazard:"AA",section:""},
    {id:615,item:"Fungsi Double Gardan (4WD)",hazard:"AA",section:""},
    {id:616,item:"Fungsi Lampu Kendaraan",hazard:"A",section:""},
    {id:617,item:"Kondisi Spion",hazard:"AA",section:""},
    {id:618,item:"Klakson",hazard:"AA",section:""},
    {id:619,item:"Wiper",hazard:"A",section:""},
    {id:620,item:"APAR",hazard:"A",section:""},
    {id:621,item:"Kotak PPGD (P3K)",hazard:"B",section:""},
    {id:622,item:"Control Panel",hazard:"A",section:""},
    {id:623,item:"Radio",hazard:"AA",section:""},
    {id:624,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:625,item:"Traffic Cone (Safety Cone)",hazard:"B",section:""},
    {id:626,item:"Wheel Chock (Ganjal Roda)",hazard:"B",section:""},
  ],
  "Motor Grader": [
    {id:701,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:702,item:"Oli Engine",hazard:"A",section:""},
    {id:703,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:704,item:"Air Radiator",hazard:"AA",section:""},
    {id:705,item:"Oli Transmisi",hazard:"A",section:""},
    {id:706,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:707,item:"Drain Water Separator",hazard:"A",section:""},
    {id:708,item:"Drain Compressor Tank",hazard:"A",section:""},
    {id:709,item:"Kondisi Blade dan Repper",hazard:"A",section:""},
    {id:710,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:711,item:"Fungsi Pedal (Brake, Inching, Akselerasi)",hazard:"AA",section:""},
    {id:712,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:713,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:714,item:"Lampu",hazard:"A",section:""},
    {id:715,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:716,item:"Wiper",hazard:"A",section:""},
    {id:717,item:"Klakson",hazard:"AA",section:""},
    {id:718,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:719,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:720,item:"Control Panel",hazard:"A",section:""},
    {id:721,item:"Radio",hazard:"AA",section:""},
    {id:722,item:"Kebersihan Ruang Kabin",hazard:"A",section:""},
    {id:723,item:"Safety Cone",hazard:"A",section:""},
    {id:724,item:"Wheel Chock",hazard:"A",section:""},
    {id:725,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:726,item:"Fog Lamp",hazard:"A",section:""},
    {id:727,item:"Commissioning",hazard:"AA",section:""},
    {id:728,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Water Truck": [
    {id:801,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:802,item:"Oli Engine",hazard:"AA",section:""},
    {id:803,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:804,item:"Air Radiator",hazard:"AA",section:""},
    {id:805,item:"Oli Transmisi",hazard:"A",section:""},
    {id:806,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:807,item:"Kondisi Tanki Air",hazard:"A",section:""},
    {id:808,item:"Kondisi Water Sprayer",hazard:"A",section:""},
    {id:809,item:"Fuel Drain",hazard:"A",section:""},
    {id:810,item:"Buang Air dari Tanki Udara",hazard:"A",section:""},
    {id:811,item:"Kondisi PTO",hazard:"A",section:""},
    {id:812,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:813,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:814,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:815,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:816,item:"Fungsi PTO",hazard:"A",section:""},
    {id:817,item:"Lampu",hazard:"A",section:""},
    {id:818,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:819,item:"Wiper",hazard:"A",section:""},
    {id:820,item:"Klakson",hazard:"AA",section:""},
    {id:821,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:822,item:"Control Panel",hazard:"A",section:""},
    {id:823,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:824,item:"Radio",hazard:"AA",section:""},
    {id:825,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:826,item:"Safety Cone",hazard:"A",section:""},
    {id:827,item:"Wheel Chock",hazard:"A",section:""},
    {id:828,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:829,item:"Emergency Stop",hazard:"A",section:""},
    {id:830,item:"Fog Lamp",hazard:"A",section:""},
    {id:831,item:"Dashcam",hazard:"A",section:""},
    {id:832,item:"Kotak P3K",hazard:"B",section:""},
  ],
};

const TYPE_FALLBACK = {
  "Crane Truck":"Dump Truck","Fuel Truck":"Water Truck","Lube Truck":"Water Truck",
  "Tyre Truck":"Dump Truck","Manhaul":"Light Vehicle","Wheel Loader":"Bulldozer"
};

const HAZARD = {
  "AA":{level:"Kritis",color:"#EF4444",bg:"rgba(239,68,68,.08)",action:"STOP — Tidak boleh dioperasikan. Lapor Supervisor."},
  "A":{level:"Tinggi",color:"#F59E0B",bg:"rgba(245,158,11,.08)",action:"Perbaiki dalam 1×12 jam. Unit boleh operasi sementara."},
  "B":{level:"Sedang",color:"#3B82F6",bg:"rgba(59,130,246,.08)",action:"Perbaiki dalam 1×24 jam. Unit boleh operasi."}
};

function getP2HItems(equipmentClass) {
  return P2H_DATA[equipmentClass] || P2H_DATA[TYPE_FALLBACK[equipmentClass]] || P2H_DATA["Dump Truck"];
}