const P2H_DATA = {
  "Articulate Truck": [
    {id:1,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:2,item:"Oli Engine",hazard:"AA",section:""},
    {id:3,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:4,item:"Air Radiator",hazard:"AA",section:""},
    {id:5,item:"Oli Transmisi",hazard:"A",section:""},
    {id:6,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:7,item:"Drain Water Separator",hazard:"B",section:""},
    {id:8,item:"Drain Compressor Tank",hazard:"B",section:""},
    {id:9,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:10,item:"Handrail / Tangga",hazard:"A",section:""},
    {id:11,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:12,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:13,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:14,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:15,item:"Lampu",hazard:"A",section:""},
    {id:16,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:17,item:"Wiper",hazard:"A",section:""},
    {id:18,item:"Klakson",hazard:"AA",section:""},
    {id:19,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:20,item:"Control Panel",hazard:"A",section:""},
    {id:21,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:22,item:"Radio",hazard:"AA",section:""},
    {id:23,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:24,item:"Safety Cone",hazard:"A",section:""},
    {id:25,item:"Wheel Chock",hazard:"A",section:""},
    {id:26,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:27,item:"Emergency Stop",hazard:"A",section:""},
    {id:28,item:"Fog Lamp",hazard:"A",section:""},
    {id:29,item:"Dashcam",hazard:"A",section:""},
    {id:30,item:"Commissioning",hazard:"AA",section:""},
    {id:31,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Bulldozer": [
    {id:1,item:"Oli Engine",hazard:"AA",section:""},
    {id:2,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:3,item:"Air Radiator",hazard:"AA",section:""},
    {id:4,item:"Oli Transmisi",hazard:"A",section:""},
    {id:5,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:6,item:"Drain Water Separator",hazard:"B",section:""},
    {id:7,item:"Kondisi Blade",hazard:"B",section:""},
    {id:8,item:"Handrail / Tangga",hazard:"A",section:""},
    {id:9,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:10,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:11,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:12,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:13,item:"Lampu",hazard:"A",section:""},
    {id:14,item:"Wiper",hazard:"A",section:""},
    {id:15,item:"Klakson",hazard:"AA",section:""},
    {id:16,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:17,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:18,item:"Control Panel",hazard:"A",section:""},
    {id:19,item:"Radio",hazard:"AA",section:""},
    {id:20,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:21,item:"Safety Cone",hazard:"A",section:""},
    {id:22,item:"Emergency Stop",hazard:"A",section:""},
    {id:23,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:24,item:"Fog Lamp",hazard:"A",section:""},
    {id:25,item:"Commissioning",hazard:"AA",section:""},
    {id:26,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Compactor": [
    {id:1,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:2,item:"Oil Engine",hazard:"AA",section:""},
    {id:3,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:4,item:"Air Radiator",hazard:"AA",section:""},
    {id:5,item:"Oil Vibrator (dalam Drum)",hazard:"A",section:""},
    {id:6,item:"Oil Hidrolik",hazard:"A",section:""},
    {id:7,item:"Fuel Drain",hazard:"B",section:""},
    {id:8,item:"Water Compressor Drain",hazard:"B",section:""},
    {id:9,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:10,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:11,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:12,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:13,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:14,item:"Lampu",hazard:"A",section:""},
    {id:15,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:16,item:"Wiper",hazard:"A",section:""},
    {id:17,item:"Klakson",hazard:"AA",section:""},
    {id:18,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:19,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:20,item:"Radio",hazard:"AA",section:""},
    {id:21,item:"Control Panel",hazard:"A",section:""},
    {id:22,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:23,item:"Safety Cone",hazard:"A",section:""},
    {id:24,item:"Wheel Chock",hazard:"A",section:""},
    {id:25,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:26,item:"Emergency Stop",hazard:"A",section:""},
    {id:27,item:"Fog Lamp",hazard:"A",section:""},
    {id:28,item:"Commissioning",hazard:"AA",section:""},
    {id:29,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Dump Truck": [
    {id:1,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:2,item:"Oli Engine",hazard:"AA",section:""},
    {id:3,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:4,item:"Air Radiator",hazard:"AA",section:""},
    {id:5,item:"Oli Transmisi",hazard:"A",section:""},
    {id:6,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:7,item:"Drain Water Separator",hazard:"B",section:""},
    {id:8,item:"Drain Compressor Tank",hazard:"B",section:""},
    {id:9,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:10,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:11,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:12,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:13,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:14,item:"Lampu",hazard:"A",section:""},
    {id:15,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:16,item:"Wiper",hazard:"A",section:""},
    {id:17,item:"Klakson",hazard:"AA",section:""},
    {id:18,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:19,item:"Control Panel",hazard:"A",section:""},
    {id:20,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:21,item:"Radio",hazard:"AA",section:""},
    {id:22,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:23,item:"Safety Cone",hazard:"A",section:""},
    {id:24,item:"Wheel Chock",hazard:"A",section:""},
    {id:25,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:26,item:"Emergency Stop",hazard:"A",section:""},
    {id:27,item:"Fog Lamp",hazard:"A",section:""},
    {id:28,item:"Dashcam",hazard:"A",section:""},
    {id:29,item:"Commissioning",hazard:"AA",section:""},
    {id:30,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Excavator": [
    {id:1,item:"Oli Engine",hazard:"AA",section:""},
    {id:2,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:3,item:"Air Radiator",hazard:"AA",section:""},
    {id:4,item:"Oli PTO",hazard:"A",section:""},
    {id:5,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:6,item:"Oli Swing",hazard:"A",section:""},
    {id:7,item:"Drain Water Separator",hazard:"B",section:""},
    {id:8,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:9,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:10,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:11,item:"Lampu",hazard:"A",section:""},
    {id:12,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:13,item:"Wiper",hazard:"A",section:""},
    {id:14,item:"Klakson",hazard:"AA",section:""},
    {id:15,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:16,item:"Control Panel",hazard:"A",section:""},
    {id:17,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:18,item:"Radio",hazard:"AA",section:""},
    {id:19,item:"Safety Cone",hazard:"A",section:""},
    {id:20,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:21,item:"Emergency Stop",hazard:"A",section:""},
    {id:22,item:"Fog Lamp",hazard:"A",section:""},
    {id:23,item:"Commissioning",hazard:"AA",section:""},
    {id:24,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Light Vehicle": [
    {id:1,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:2,item:"Level Oli Engine",hazard:"AA",section:""},
    {id:3,item:"Air Radiator",hazard:"AA",section:""},
    {id:4,item:"Level Oli Steering",hazard:"A",section:""},
    {id:5,item:"Level Oli Rem (Break Oil)",hazard:"A",section:""},
    {id:6,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:7,item:"Lampu Rotary (Strobe Lamp)",hazard:"AA",section:""},
    {id:8,item:"Buggy Whip",hazard:"AA",section:""},
    {id:9,item:"Kondisi Battery / Accu",hazard:"A",section:""},
    {id:10,item:"Air Wiper",hazard:"A",section:""},
    {id:11,item:"Kebersihan Alat",hazard:"B",section:""},
    {id:12,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:13,item:"Fungsi Steering / Reaksi Kemudi",hazard:"AA",section:""},
    {id:14,item:"Fungsi Seat Belt / Sabuk Pengaman",hazard:"AA",section:""},
    {id:15,item:"Fungsi Double Gardan (4WD)",hazard:"AA",section:""},
    {id:16,item:"Fungsi Lampu Kendaraan",hazard:"A",section:""},
    {id:17,item:"Kondisi Spion",hazard:"AA",section:""},
    {id:18,item:"Klakson",hazard:"AA",section:""},
    {id:19,item:"Wiper",hazard:"A",section:""},
    {id:20,item:"APAR",hazard:"A",section:""},
    {id:21,item:"Kotak PPGD (P3K)",hazard:"B",section:""},
    {id:22,item:"Control Panel",hazard:"A",section:""},
    {id:23,item:"Radio",hazard:"AA",section:""},
    {id:24,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:25,item:"Traffic Cone (Safety Cone)",hazard:"B",section:""},
    {id:26,item:"Wheel Chock (Ganjal Roda)",hazard:"B",section:""},
  ],
  "Motor Grader": [
    {id:1,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:2,item:"Oli Engine",hazard:"A",section:""},
    {id:3,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:4,item:"Air Radiator",hazard:"AA",section:""},
    {id:5,item:"Oli Transmisi",hazard:"A",section:""},
    {id:6,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:7,item:"Drain Water Separator",hazard:"A",section:""},
    {id:8,item:"Drain Compressor Tank",hazard:"A",section:""},
    {id:9,item:"Kondisi Blade dan Repper",hazard:"A",section:""},
    {id:10,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:11,item:"Fungsi Pedal (Brake, Inching, Akselerasi)",hazard:"AA",section:""},
    {id:12,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:13,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:14,item:"Lampu",hazard:"A",section:""},
    {id:15,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:16,item:"Wiper",hazard:"A",section:""},
    {id:17,item:"Klakson",hazard:"AA",section:""},
    {id:18,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:19,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:20,item:"Control Panel",hazard:"A",section:""},
    {id:21,item:"Radio",hazard:"AA",section:""},
    {id:22,item:"Kebersihan Ruang Kabin",hazard:"A",section:""},
    {id:23,item:"Safety Cone",hazard:"A",section:""},
    {id:24,item:"Wheel Chock",hazard:"A",section:""},
    {id:25,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:26,item:"Fog Lamp",hazard:"A",section:""},
    {id:27,item:"Commissioning",hazard:"AA",section:""},
    {id:28,item:"Kotak P3K",hazard:"B",section:""},
  ],
  "Water Truck": [
    {id:1,item:"Ban & Baut Roda",hazard:"A",section:""},
    {id:2,item:"Oli Engine",hazard:"AA",section:""},
    {id:3,item:"Kerusakan Akibat Insiden",hazard:"A",section:""},
    {id:4,item:"Air Radiator",hazard:"AA",section:""},
    {id:5,item:"Oli Transmisi",hazard:"A",section:""},
    {id:6,item:"Oli Hidrolik",hazard:"A",section:""},
    {id:7,item:"Kondisi Tanki Air",hazard:"A",section:""},
    {id:8,item:"Kondisi Water Sprayer",hazard:"A",section:""},
    {id:9,item:"Fuel Drain",hazard:"A",section:""},
    {id:10,item:"Buang Air dari Tanki Udara",hazard:"A",section:""},
    {id:11,item:"Kondisi PTO",hazard:"A",section:""},
    {id:12,item:"Kelainan Saat Operasi Sebelumnya",hazard:"A",section:""},
    {id:13,item:"Fungsi Brake",hazard:"AA",section:""},
    {id:14,item:"Fungsi Steering",hazard:"AA",section:""},
    {id:15,item:"Fungsi Seat Belt",hazard:"AA",section:""},
    {id:16,item:"Fungsi PTO",hazard:"A",section:""},
    {id:17,item:"Lampu",hazard:"A",section:""},
    {id:18,item:"Fungsi Mirror (Spion)",hazard:"A",section:""},
    {id:19,item:"Wiper",hazard:"A",section:""},
    {id:20,item:"Klakson",hazard:"AA",section:""},
    {id:21,item:"Fire Suppression / APAR",hazard:"A",section:""},
    {id:22,item:"Control Panel",hazard:"A",section:""},
    {id:23,item:"Alarm Mundur",hazard:"AA",section:""},
    {id:24,item:"Radio",hazard:"AA",section:""},
    {id:25,item:"Kebersihan Ruang Kabin",hazard:"B",section:""},
    {id:26,item:"Safety Cone",hazard:"A",section:""},
    {id:27,item:"Wheel Chock",hazard:"A",section:""},
    {id:28,item:"Fatigue Alarm",hazard:"AA",section:""},
    {id:29,item:"Emergency Stop",hazard:"A",section:""},
    {id:30,item:"Fog Lamp",hazard:"A",section:""},
    {id:31,item:"Dashcam",hazard:"A",section:""},
    {id:32,item:"Kotak P3K",hazard:"B",section:""},
  ],
};

// Unit types yang belum ada checklist → pakai yang sejenis
const TYPE_FALLBACK = {
  "Crane Truck":"Dump Truck","Fuel Truck":"Water Truck","Lube Truck":"Water Truck",
  "Tyre Truck":"Dump Truck","Manhaul":"Light Vehicle","Wheel Loader":"Bulldozer"
};

const HAZARD = {
  "AA":{level:"Kritis",color:"#EF4444",bg:"rgba(239,68,68,.08)",action:"STOP — Tidak boleh dioperasikan. Lapor Supervisor."},
  "A":{level:"Tinggi",color:"#F59E0B",bg:"rgba(245,158,11,.08)",action:"Perbaiki dalam 1×12 jam. Unit boleh operasi sementara."},
  "B":{level:"Sedang",color:"#3B82F6",bg:"rgba(59,130,246,.08)",action:"Perbaiki dalam 1×24 jam. Unit boleh operasi."}
};

function getP2HItems(equipmentClass) {
  return P2H_DATA[equipmentClass] || P2H_DATA[TYPE_FALLBACK[equipmentClass]] || P2H_DATA["Dump Truck"];
}